# Generated by Django 6.0.2 on 2026-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(max_length=20)),
                ('cgpa', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(default='fa-university', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('description', models.TextField(help_text='Each bullet on a new line')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-hospital', 'Hospital'), ('fa-briefcase', 'Briefcase'), ('fa-share-alt', 'Social Media'), ('fa-apple-alt', 'Food/Health'), ('fa-wallet', 'Finance'), ('fa-code', 'Code'), ('fa-globe', 'Web'), ('fa-database', 'Database')], default='fa-code', max_length=50)),
                ('technologies', models.CharField(help_text='Comma separated: Django, MySQL, Bootstrap', max_length=300)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-server', 'Server / Backend'), ('fa-plug', 'API'), ('fa-database', 'Database'), ('fa-shield-alt', 'Security'), ('fa-code', 'Code'), ('fa-cogs', 'Settings / DevOps'), ('fa-globe', 'Web'), ('fa-vial', 'Testing')], default='fa-code', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Programming Languages'), ('framework', 'Backend Frameworks'), ('database', 'Databases'), ('web', 'Web Technologies'), ('tool', 'Tools & Version Control'), ('practice', 'Dev Practices')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
